#pragma once

// M5Stack StackChan / CoreS3 pin map.

#include <driver/gpio.h>

#define STACKCHAN_I2C_SDA_PIN GPIO_NUM_12
#define STACKCHAN_I2C_SCL_PIN GPIO_NUM_11

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_0
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_33
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_34
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_14
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_13

#define BUILTIN_LED_GPIO        GPIO_NUM_NC
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

#define DISPLAY_SDA_PIN GPIO_NUM_NC
#define DISPLAY_SCL_PIN GPIO_NUM_NC
#define DISPLAY_WIDTH   320
#define DISPLAY_HEIGHT  240
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false

#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_NC
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT true

#define DISPLAY_SPI_MOSI_PIN GPIO_NUM_37
#define DISPLAY_SPI_MISO_PIN GPIO_NUM_NC
#define DISPLAY_SPI_SCLK_PIN GPIO_NUM_36
#define DISPLAY_PANEL_CS_PIN GPIO_NUM_3
#define DISPLAY_PANEL_DC_PIN GPIO_NUM_35

// Camera pins.
#define CAMERA_PIN_PWDN  GPIO_NUM_NC
#define CAMERA_PIN_RESET GPIO_NUM_NC
#define CAMERA_PIN_XCLK  GPIO_NUM_NC
#define CAMERA_PIN_SIOD  GPIO_NUM_NC
#define CAMERA_PIN_SIOC  GPIO_NUM_NC
#define CAMERA_PIN_D0    GPIO_NUM_39
#define CAMERA_PIN_D1    GPIO_NUM_40
#define CAMERA_PIN_D2    GPIO_NUM_41
#define CAMERA_PIN_D3    GPIO_NUM_42
#define CAMERA_PIN_D4    GPIO_NUM_15
#define CAMERA_PIN_D5    GPIO_NUM_16
#define CAMERA_PIN_D6    GPIO_NUM_48
#define CAMERA_PIN_D7    GPIO_NUM_47
#define CAMERA_PIN_VSYNC GPIO_NUM_46
#define CAMERA_PIN_HREF  GPIO_NUM_38
#define CAMERA_PIN_PCLK  GPIO_NUM_45

// Compatibility aliases for retained runtime and audio codec code.
#define AUDIO_CODEC_I2C_SDA_PIN STACKCHAN_I2C_SDA_PIN
#define AUDIO_CODEC_I2C_SCL_PIN STACKCHAN_I2C_SCL_PIN
